### ISSUE TITLE
Highlighting does not work when pwd is not git-root

### ISSUE THREAD

**Issue by jandamm** [kristijanhusak/vim-dirvish-git#6]
I'm using vim-rooter to have my pwd always at the root of the project.
While this is the git root for most projects, it isn't for my dotfiles.
Opening nvim from the `~/.dotfiles` works fine, but when I traverse into `~/.dotfiles/vim` it does not.
`l:status` then contains `... vim/init.vim` which is not found because `vim` is also part of the pwd.
So `vim-dirvish-git` is probably looking for `~/.dotfiles/vim/vim/init.vim`.

**Comment by yous** [comment]
#8 is merged now, so you can have a check. Current implementation has a limitation: it doesn't track the status of other git repository which is not the git repository detected when dirvish is opened.

**Comment by jandamm** [comment]
In the meantime I've changed my dotfiles repo and it now doesn't contain submodules anymore.
But looking at the diff it should work now 👍
