### ISSUE TITLE
Highlight icon

### ISSUE THREAD

**Issue by gegoune** [kristijanhusak/vim-dirvish-git#7]
Hi, trying to make your plugin and https://github.com/kyazdani42/nvim-tree.lua look more alike (highlights and icons).

Got pretty close results, but one thing that stands out is that nvim-tree highlights icon as well as filename while vim-dirvish-git does not.

nvim-tree:
<img width="198" alt="Screenshot 2021-03-26 at 21 54 44" src="https://user-images.githubusercontent.com/69750637/112685903-e2ad5a80-8e7d-11eb-856b-0c418fc1fbd1.png">

vim-dirvish-git:
<img width="196" alt="Screenshot 2021-03-26 at 21 55 49" src="https://user-images.githubusercontent.com/69750637/112686015-083a6400-8e7e-11eb-8b0e-21ebe7791c61.png">

Do you think it would be possible to highlight icons as well?

**Comment by kristijanhusak** [comment]
Hi,

Dirvish uses `conceal` feature to show the icons, so we cannot have multiple highlight groups for that. You can just change `Conceal` highlight group that will affect all icons.

**Comment by gegoune** [comment]
That's a shame, but thanks for rapid answer!
